#!/usr/bin/env bash
# =============================================================================
# setup_system.sh — configure a new Pi (or re-apply settings after a reinstall)
# =============================================================================
# Run once on a fresh machine:
#   bash setup_system.sh
#
# What it does:
#   1. Writes udev rules so USB devices get stable symlinks (/dev/esp32, /dev/lidar)
#   2. Adds the ROS2 environment to ~/.bashrc (domain ID, peer discovery)
#   3. Adds the pi user to the dialout group (serial port access without sudo)
#   4. Verifies symlinks appear after udev reload
#
# All values come from system.env — edit that file first if hardware changes.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/system.env"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE not found. Run this script from the repo root."
    exit 1
fi

# shellcheck source=system.env
source "$ENV_FILE"

echo "=== DARO System Setup ==="
echo "    ESP32 USB serial : $ESP32_USB_SERIAL -> $ESP32_SYMLINK"
echo "    LiDAR USB serial : $LIDAR_USB_SERIAL -> $LIDAR_SYMLINK"
echo "    ROS_DOMAIN_ID    : $ROS_DOMAIN_ID"
echo "    Pi IP            : $PI_IP"
echo ""

# -----------------------------------------------------------------------------
# 1. udev rules — stable /dev/esp32 and /dev/lidar symlinks
# -----------------------------------------------------------------------------
UDEV_RULES="/etc/udev/rules.d/99-daro-serial.rules"
echo "--- Writing $UDEV_RULES ..."

sudo tee "$UDEV_RULES" > /dev/null <<EOF
# DARO udev rules — generated by setup_system.sh
# Source of truth: system.env
# Re-run setup_system.sh to regenerate after hardware changes.

# ESP32 — always $ESP32_SYMLINK
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", \\
    ATTRS{serial}=="$ESP32_USB_SERIAL", \\
    SYMLINK+="esp32", MODE="0666"

# LiDAR — always $LIDAR_SYMLINK
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", \\
    ATTRS{serial}=="$LIDAR_USB_SERIAL", \\
    SYMLINK+="lidar", MODE="0666"
EOF

echo "    Reloading udev rules..."
sudo udevadm control --reload-rules
sudo udevadm trigger
sleep 1

# Verify
echo "    Checking symlinks..."
for LINK in "$ESP32_SYMLINK" "$LIDAR_SYMLINK"; do
    if [[ -L "$LINK" ]]; then
        echo "    OK: $LINK -> $(readlink "$LINK")"
    else
        echo "    WARNING: $LINK not found — replug the device and re-run this script"
    fi
done


# -----------------------------------------------------------------------------
# 2. dialout group — serial port access without sudo
# -----------------------------------------------------------------------------
if ! groups "$USER" | grep -q dialout; then
    echo ""
    echo "--- Adding $USER to dialout group..."
    sudo usermod -aG dialout "$USER"
    echo "    NOTE: Log out and back in (or reboot) for group change to take effect."
else
    echo ""
    echo "--- $USER already in dialout group. OK."
fi


# -----------------------------------------------------------------------------
# 3. ROS2 environment — append to ~/.bashrc if not already present
# -----------------------------------------------------------------------------
BASHRC="$HOME/.bashrc"
ROS_SETUP_MARKER="# DARO ROS2 setup (added by setup_system.sh)"

if grep -qF "$ROS_SETUP_MARKER" "$BASHRC" 2>/dev/null; then
    echo ""
    echo "--- ROS2 env already in $BASHRC. Skipping."
else
    echo ""
    echo "--- Adding ROS2 environment to $BASHRC ..."
    cat >> "$BASHRC" <<EOF

$ROS_SETUP_MARKER
source /opt/ros/jazzy/setup.bash
source $SCRIPT_DIR/pi/daro_ros2_ws/install/setup.bash 2>/dev/null || true
export ROS_DOMAIN_ID=$ROS_DOMAIN_ID
EOF
    echo "    Done. Run 'source ~/.bashrc' or open a new terminal to apply."
fi


# -----------------------------------------------------------------------------
# 4. Done
# -----------------------------------------------------------------------------
echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. If dialout group was just added: log out and back in (or reboot)"
echo "  2. Build the ROS2 workspace if not already built:"
echo "       cd $SCRIPT_DIR/pi/daro_ros2_ws"
echo "       colcon build --symlink-install"
echo "       source install/setup.bash"
echo "  3. Launch the robot:"
echo "       ros2 launch daro_bringup robot.launch.py"
